default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
development:
  <<: *default
  database: myapp__development
  username: rails_dev
  password: aqwe123
  host: localhost
  port: 5432

test:
  <<: *default
  database: myapp_test
  host: localhost
  port: 5432
  username: rails_dev
  password: aqwe123

production:
  <<: *default
  database: myapp_production
  username: my_app
  password:
